# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: 
  - osx

language: R
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
